version: '3.1'

services:
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7.10.0
    container_name: tinder_elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.io/bitnami/kibana:7.10.0
    container_name: tinder_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://tinder_elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
